//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectProgressExport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("进展项目-临床试验")]
        public string txtExcelClinicalSheetName {
            get {
                return ((string)(this["txtExcelClinicalSheetName"]));
            }
            set {
                this["txtExcelClinicalSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("项目名称")]
        public string txtExcelClinicalProjectColumnName {
            get {
                return ((string)(this["txtExcelClinicalProjectColumnName"]));
            }
            set {
                this["txtExcelClinicalProjectColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("医学支持内容/后续计划")]
        public string txtExcelClinicalMedicalColumnName {
            get {
                return ((string)(this["txtExcelClinicalMedicalColumnName"]));
            }
            set {
                this["txtExcelClinicalMedicalColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("统计支持内容/后续计划")]
        public string txtExcelClinicalStatisticsColumnName {
            get {
                return ((string)(this["txtExcelClinicalStatisticsColumnName"]));
            }
            set {
                this["txtExcelClinicalStatisticsColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DM支持内容/后续计划")]
        public string txtExcelClinicalDataManageColumnName {
            get {
                return ((string)(this["txtExcelClinicalDataManageColumnName"]));
            }
            set {
                this["txtExcelClinicalDataManageColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("一、临床试验-项目进度")]
        public string txtExcelClinicalTitle {
            get {
                return ((string)(this["txtExcelClinicalTitle"]));
            }
            set {
                this["txtExcelClinicalTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("进展项目-CER或其他")]
        public string txtExcelCERSheetName {
            get {
                return ((string)(this["txtExcelCERSheetName"]));
            }
            set {
                this["txtExcelCERSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("项目名称")]
        public string txtExcelCERProjectColumnName {
            get {
                return ((string)(this["txtExcelCERProjectColumnName"]));
            }
            set {
                this["txtExcelCERProjectColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("医学支持内容/后续计划")]
        public string txtExcelCERMedicalColumnName {
            get {
                return ((string)(this["txtExcelCERMedicalColumnName"]));
            }
            set {
                this["txtExcelCERMedicalColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("统计支持内容/后续计划")]
        public string txtExcelCERStatisticsColumnName {
            get {
                return ((string)(this["txtExcelCERStatisticsColumnName"]));
            }
            set {
                this["txtExcelCERStatisticsColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("二、CER-项目进度")]
        public string txtExcelCERTitle {
            get {
                return ((string)(this["txtExcelCERTitle"]));
            }
            set {
                this["txtExcelCERTitle"] = value;
            }
        }
    }
}
